name: request_test
description: "just testing requests"

# API Configuration
api_endpoint: "https://a061igc186.execute-api.us-east-1.amazonaws.com/dev"
api_key: "blocked"
model: "us.anthropic.claude-3-haiku-20240307-v1:0"
temperature: 0.3
session_id: "schneider_stats_session"

# RAG Settings
rag_usage: false
rag_threshold: 0.5
rag_k: 0

# Estimation Settings
num_iterations: 10
epsilon: 0.1

# PostgreSQL Statistics Configuration
target_columns:
  stanullfrac: 3    # null fraction column index
  stadistinct: 5    # distinct values column index  
  stanumbers1: 21   # statistical numbers array column index

# Prompts - Updated for better CSV compatibility
system_prompt: "You are an old sailor."

estimation_prompt: |
  Tell me a joke.

# Validation Settings
accuracy_threshold: 80.0
max_retries: 3 