name: proxy
description: "Schneider AI statistics estimation configuration"

# Provider Configuration - can be "llmproxy" or "openai"
provider: "llmproxy"
model: "us.anthropic.claude-3-haiku-20240307-v1:0"
temperature: 0.3
session_id: "schneider_stats_session"

# RAG Settings
rag_usage: false
rag_threshold: 0.5
rag_k: 0

# Estimation Settings
num_iterations: 10
epsilon: 0.1

# PostgreSQL Statistics Configuration
target_columns:
  stanullfrac: 3    # null fraction column index (position 3 in pg_statistic)
  stadistinct: 5    # distinct values column index (position 5 in pg_statistic)
  stanumbers1: 16   # statistical numbers array column index (position 16 in pg_statistic, NOT 21!)

# Prompts - Updated for better CSV compatibility
system_prompt: "You are an expert PostgreSQL statistics estimator. You analyze database schemas and generate accurate pg_stats predictions. Always output semicolon-separated CSV format with no additional text. Base your estimates on common database patterns and the specific context provided. Never use random values."

estimation_prompt: |
  Generate PostgreSQL pg_stats estimates for the following database. Output ONLY semicolon-separated CSV.
  
  CRITICAL REQUIREMENTS:
  - Use semicolons (;) as separators, NOT commas
  - Include all columns listed below
  - Base estimates on the actual data patterns and column purposes
  
  Column definitions:
  - attname: table.column name format
  - null_frac: Fraction of NULL values (0.0-1.0)
  - avg_width: Average width in bytes
  - n_distinct: IMPORTANT - Follow these rules:
    * Primary keys, unique columns: -1.0 (negative one)
    * Foreign keys: Positive number matching referenced table size
    * Boolean columns: 2 or 3 (for true/false/null)
    * Status/enum columns: Small positive number (2-20)
    * Text columns: Large positive number or negative fraction
    * Timestamps: Large negative fraction (e.g., -0.9)
    * Use negative values for columns that grow with table size
  - most_common_vals: Array of most frequent values in brackets, e.g., [value1;value2;value3]
  - most_common_freqs: Array of frequencies matching most_common_vals, e.g., [0.4;0.3;0.2]
  - histogram_bounds: Array of values dividing data into equal buckets (exclude most_common_vals)
  - correlation: IMPORTANT - Estimate based on:
    * Primary keys with auto-increment: 0.99 to 1.0
    * Timestamps (creation dates): 0.9 to 1.0
    * Random UUIDs: -0.1 to 0.1
    * Foreign keys: 0.0 to 0.5
    * Status columns: -0.2 to 0.2
    * Updated timestamps: 0.0 to 0.3
    * Consider if data is likely inserted sequentially or randomly
  
  Database context:
  - Columns: {col_names}
  - Database size: {size}
  - Schema details: {sample_data}
  
  Analyze the column names, types, and relationships to generate realistic statistics.
  For n_distinct and correlation, consider the column's purpose and typical usage patterns.

# Validation Settings
accuracy_threshold: 80.0
max_retries: 3 