name: default
description: "Default PostgreSQL runtime settings configuration"
analyze_verbose: true
analyze_timeout_seconds: 300
clear_caches: true
reset_counters: true
work_mem: "16MB"
maintenance_work_mem: "16MB"
stats_reset_strategy: "once"
transaction_handling: "rollback" 