name: "Default Empty PG Stats"
description: "Clears all caches and statistics counters in PostgreSQL. Does not run ANALYZE."
message: "Empty PG Stats - clears caches and counters without running ANALYZE" 