name: fast
description: "Fast PostgreSQL statistics with reduced timeouts"
settings:
  analyze_verbose: false
  analyze_timeout_seconds: 60
  clear_caches: false
  reset_counters: false
  work_mem: "8MB"
  maintenance_work_mem: "8MB" 
data:
  message: "This is a test message. Settings are generally determine the enviroment, but data is for other aspects of the program (epsilon, prompts, etc)"