name: fast
description: "Fast PostgreSQL statistics with reduced timeouts"
message: "This is a test message. Settings are generally determine the enviroment, but data is for other aspects of the program (epsilon, prompts, etc)"