name: aggressive
description: "Aggressive random statistics with wide range values"
settings:
  min_stats_value: 1
  max_stats_value: 50000
  analyze_verbose: true
  analyze_timeout_seconds: 600
  clear_caches: true
  reset_counters: true
  work_mem: "32MB"
  maintenance_work_mem: "64MB"
  skip_system_schemas: true
  excluded_schemas:
    - "information_schema"
    - "pg_catalog" 