name: conservative
description: "Conservative random statistics with smaller range values"
settings:
  min_stats_value: 100
  max_stats_value: 1000
  analyze_verbose: false
  analyze_timeout_seconds: 180
  clear_caches: true
  reset_counters: true
  work_mem: "8MB"
  maintenance_work_mem: "16MB"
  skip_system_schemas: true
  excluded_schemas:
    - "information_schema"
    - "pg_catalog" 